import networkx as nx

# PHYSICAL PLACES
MAIN_BUILDING = "MAIN_BUILDING"
CLASSROOM_8_104 = "CLASSROOM_8_104"
STAIRS_1 = "STAIRS_1"

ADMINISTRATIVE_BUILDING = "ADMINISTRATIVE_BUILDING"
LIBRARY_BUILDING = "LIBRARY_BUILDING"
OTHER_BUILDING = "OTHER_BUILDING"
STREETS = "STREETS"


# GENERAL POINTS
MAIN_ENTRANCE = "MAIN_ENTRANCE"
N1_1 = "N1_1"
N1_2 = "N1_2"
N1_3 = "N1_3"

# STREETS NODES
CARRERA_16_40A = "CARRERA_16_40A"
MULKY_STUDIO = "MULKY_STUDIO"
CALLE_40_18 = "CALLE_40_18"
CALLE_40_18A = "CALLE_40_18A"


# NODES NAMES
MAIN_BUILDING_MAIN_ENTRANCE = f"{MAIN_BUILDING}_{MAIN_ENTRANCE}"
OTHER_BUILDING_MAIN_ENTRANCE = f"{OTHER_BUILDING}_{MAIN_ENTRANCE}"
STREETS_CARRERA_16_40A = f"{STREETS}_{CARRERA_16_40A}"
ADMINISTRATIVE_BUILDING_MAIN_ENTRANCE = f"{ADMINISTRATIVE_BUILDING}_{MAIN_ENTRANCE}"
STREETS_MULKY_STUDIO = f"{STREETS}_{MULKY_STUDIO}"
STREETS_CALLE_40_18 = f"{STREETS}_{CALLE_40_18}"
STREETS_CALLE_40_18A = f"{STREETS}_{CALLE_40_18A}"
LIBRARY_BUILDING_MAIN_ENTRANCE = f"{LIBRARY_BUILDING}_{MAIN_ENTRANCE}"
MAIN_BUILDING_CLASROOM_8_104 = f"{MAIN_BUILDING}_{CLASSROOM_8_104}"
MAIN_BUILDING_N1_1 = f"{MAIN_BUILDING}_{N1_1}"
MAIN_BUILDING_N1_2 = f"{MAIN_BUILDING}_{N1_2}"
MAIN_BUILDING_N1_3 = f"{MAIN_BUILDING}_{N1_3}"
MAIN_BUILDING_STAIRS_1 = f"{MAIN_BUILDING}_{STAIRS_1}"


def crear_grafo_universidad():

    G = nx.Graph()

    G.add_node(MAIN_BUILDING_MAIN_ENTRANCE)
    G.add_node(OTHER_BUILDING_MAIN_ENTRANCE)
    G.add_node(STREETS_CARRERA_16_40A)
    G.add_node(ADMINISTRATIVE_BUILDING_MAIN_ENTRANCE)
    G.add_node(STREETS_MULKY_STUDIO)
    G.add_node(STREETS_CALLE_40_18)
    G.add_node(STREETS_CALLE_40_18A)
    G.add_node(LIBRARY_BUILDING_MAIN_ENTRANCE)
    G.add_node(MAIN_BUILDING_CLASROOM_8_104)
    G.add_node(MAIN_BUILDING_N1_1)
    G.add_node(MAIN_BUILDING_N1_2)
    G.add_node(MAIN_BUILDING_N1_3)
    G.add_node(MAIN_BUILDING_STAIRS_1)

    G.add_edge(MAIN_BUILDING_MAIN_ENTRANCE, STREETS_CARRERA_16_40A, weight=10)
    G.add_edge(OTHER_BUILDING_MAIN_ENTRANCE, STREETS_CARRERA_16_40A, weight=12)
    G.add_edge(STREETS_CARRERA_16_40A,
               ADMINISTRATIVE_BUILDING_MAIN_ENTRANCE, weight=18)
    G.add_edge(STREETS_CARRERA_16_40A, MULKY_STUDIO, weight=40)
    G.add_edge(MULKY_STUDIO, STREETS_CALLE_40_18, weight=10)
    G.add_edge(STREETS_CALLE_40_18, STREETS_CALLE_40_18A, weight=10)
    G.add_edge(STREETS_CALLE_40_18A, LIBRARY_BUILDING_MAIN_ENTRANCE, weight=5)
    G.add_edge(MAIN_BUILDING_MAIN_ENTRANCE, MAIN_BUILDING_N1_1, weight=10)
    G.add_edge(MAIN_BUILDING_N1_1, MAIN_BUILDING_N1_2, weight=10)
    G.add_edge(MAIN_BUILDING_N1_2, MAIN_BUILDING_N1_3, weight=7)
    G.add_edge(MAIN_BUILDING_N1_3, MAIN_BUILDING_CLASROOM_8_104, weight=5)

    return G


G = crear_grafo_universidad()


def ruta_mas_corta(grafo, origen, destino):
    return nx.shortest_path(grafo, source=origen, target=destino, weight='weight')
